### ISSUE TITLE
Billing address "Magento Order"

### ISSUE THREAD

**Issue by clicktrend** [ibnab/orocrm-pdfmanager#3]
I want to generate an invoice. How can I access the billing information of a magento order? I don't find any variable in template data.

**Comment by clicktrend** [comment]
OneToMany relations are not shown.

**Comment by ibnab** [comment]
i think this issue is from orocrm it's self try inisde email template if have the same problem ... if yes we open issue iniside orocrm channel

**Comment by clicktrend** [comment]
Look here http://www.orocrm.com/forums/topic/onetomany-relations-in-email-templates
It's not supported

**Comment by ibnab** [comment]
it's need more effort from oro core but in next version of our extension wewill try how resolve this issue  just the order ...

**Comment by roldan** [comment]
Hi, is there any news about this feature? I know that is "oro-core-related" but maybe you've found a workaround. Anyway, i've posted on oro forum too:

https://www.orocrm.com/forums/topic/onetomany-relations-in-email-templates#post-21117 

Thanks

**Comment by ibnab** [comment]
we resolve for pdf-manager and email (subtemplate) for email it maybe we lunch as open plugin but for pdf manager is with pro version
